services:
  - type: web
    name: litsphere-backend
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && npx prisma generate
    startCommand: node Backend/server.js
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        value: "LitSphere Security <mostafakamal.cse2022@gmail.com>"
      - key: REDIS_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false
